import pandas as pd

data = [
    {
        'job_id': 1,
        'title': 'Marketing Intern',
        'location': 'US NY New York',
        'department': 'Marketing',
        'salary_range': '',
        'company_profile': 'We are Food52.',
        'description': 'Food52, a fast-growing, James Beard Award-winning online food community...',
        'requirements': 'Experience with content management systems a major plus...',
        'benefits': '',
        'telecommuting': 0,
        'has_company_logo': 1,
        'has_questions': 0,
        'employment_type': 'Other',
        'required_experience': 'Internship',
        'required_education': '',
        'industry': '',
        'function': '',
        'fraudulent': 0
    },
    {
        'job_id': 2,
        'title': 'Customer Service - Cloud Video Production',
        'location': 'NZ',
        'department': '',
        'salary_range': '',
        'company_profile': '90 Seconds, the worlds Cloud Video Production Service...',
        'description': 'Organised - Focused - Vibrant - Awesome!...',
        'requirements': 'What we expect from you:...',
        'benefits': 'What you will get from us...',
        'telecommuting': 0,
        'has_company_logo': 1,
        'has_questions': 0,
        'employment_type': 'Full-time',
        'required_experience': 'Not Applicable',
        'required_education': '',
        'industry': '',
        'function': 'Customer Service',
        'fraudulent': 0
    },
    {
        'job_id': 3,
        'title': 'Commissioning Machinery Assistant (CMA)',
        'location': 'US IA Wever',
        'department': '',
        'salary_range': '',
        'company_profile': 'Valor Services provides Workforce Solutions...',
        'description': 'Our client, an international technology and engineering company...',
        'requirements': 'Implement pre-commissioning and commissioning procedures...',
        'benefits': '',
        'telecommuting': 0,
        'has_company_logo': 1,
        'has_questions': 0,
        'employment_type': '',
        'required_experience': '',
        'required_education': '',
        'industry': '',
        'function': '',
        'fraudulent': 0
    },
    {
        'job_id': 4,
        'title': 'Account Executive - Washington DC',
        'location': 'US DC Washington',
        'department': 'Sales',
        'salary_range': '',
        'company_profile': 'Our passion for improving quality of life...',
        'description': 'THE COMPANY: ESRI – Environmental Systems Research Institute...',
        'requirements': 'EDUCATION/EXPERIENCE:...',
        'benefits': 'Our culture is one of the things that sets us apart...',
        'telecommuting': 0,
        'has_company_logo': 1,
        'has_questions': 0,
        'employment_type': 'Full-time',
        'required_experience': 'Mid-Senior level',
        'required_education': 'Bachelor\'s Degree',
        'industry': 'Computer Software',
        'function': 'Sales',
        'fraudulent': 0
    },
    {
        'job_id': 5,
        'title': 'Bill Review Manager',
        'location': 'US FL Fort Worth',
        'department': '',
        'salary_range': '',
        'company_profile': 'SpotSource Solutions LLC is a Global Human Capital Management...',
        'description': 'JOB TITLE: Bill Review Manager...',
        'requirements': 'Bachelor\'s degree in a related field...',
        'benefits': 'Competitive salary...',
        'telecommuting': 0,
        'has_company_logo': 1,
        'has_questions': 1,
        'employment_type': 'Full-time',
        'required_experience': 'Mid-Senior level',
        'required_education': 'Bachelor\'s Degree',
        'industry': 'Hospital & Health Care',
        'function': 'Health Care Provider',
        'fraudulent': 1
    },
    {
        'job_id': 6,
        'title': 'Accounting Clerk',
        'location': 'US MD',
        'department': '',
        'salary_range': '',
        'company_profile': '',
        'description': 'Job Description\nWe are looking for a skilled Accounting Clerk...',
        'requirements': 'Proven accounting experience...',
        'benefits': '',
        'telecommuting': 0,
        'has_company_logo': 0,
        'has_questions': 0,
        'employment_type': 'Full-time',
        'required_experience': 'Entry level',
        'required_education': 'High School or equivalent',
        'industry': 'Accounting',
        'function': 'Accounting/Auditing',
        'fraudulent': 1
    }
]

# Duplicate data to ensure enough rows
data = data * 3  # 18 rows

df = pd.DataFrame(data)
df.to_csv('fake_job_postings.csv', index=False)
print("Created fake_job_postings.csv with", len(df), "rows")
